### ISSUE TITLE
Main.css does not get hashed on production build

### ISSUE THREAD

**Issue by jounileander** [strarsis/sage#1]
build:production does not hash css-file. Also getting hashed assets with @asset only return un-hashed url even though file is found from assets.json.

Any ideas?

**Comment by strarsis** [comment]
@jounileander: Are you using the webpack4 or the webpack5 branch?

**Comment by jounileander** [comment]
Hi.

Using Webpack5 branch. But actually found fix already.

On [webpack.config.js](https://github.com/strarsis/sage/blob/webpack5/resources/assets/build/webpack.config.js) row 171 needs to be
`filename: `styles/${assetsFilenames}.css`,`
Instead of
`filename: 'styles/[name].css',`

**Comment by strarsis** [comment]
@jounileander: Thanks for the feedback. Some users reported isseus with BrowserSync reload loops (and Sage routing).
Do you have the same issue?

**Comment by strarsis** [comment]
@jounileander: You can now try the whole feature branch ("9.2") using `composer create-project`: 
https://discourse.roots.io/t/sage-9-2-please-test/20067?u=strarsis
